version: 0.2
 phases:
   install:
     commands:
       - echo install aws cli v2
       - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
       - unzip awscliv2.zip
       - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update
   pre_build:
     commands:
       - export TZ="Asia/Tokyo"
   build:
     commands:
       - echo create ami
       - sh ./get_ami.sh
 post_build:
     commands:
       - echo Build completed on date
